#ifndef __CONFIG_H__
#define __CONFIG_H__

#define TITLE "Plane War"
#define SCREEN_WIDTH 450
#define SCREEN_HEIGHT 700
#define GAME_FPS 60
#define IMG_FORMAT SDL_PIXELFORMAT_RGBA32

#define ALIVE_SCORE 10
#define ALIVE_INTERVAL 1000
#define AIRCRAFT_DOWN_INTERVAL 100
#define BACKGROUND_SCROLL_SPEED 1

#define P_ENEMY0 0.025
#define P_ENEMY1 0.015
#define P_ENEMY2 0.002

#define BORDER_X 20
#define BORDER_Y 30
#define BORDER_TEXT 5

#define START 0
#define PLAYING 1
#define PAUSE 2
#define END 3

#define TITLE_POSITION 210
#define INFO_POSITION 525
#define SCORE_POSITION 280
#define BEST_SCORE_POSITION 315

#define INFO_MAX_LEN 30
#define TEXT_RECT_WIDTH 300
#define TEXT_RECT_HEIGHT 50
#define TITLE_FONT_SIZE 25
#define INFO_FONT_SIZE 17

#define HERO_WIDTH 50
#define HERO_HEIGHT 62
#define HERO_SPEED 6
#define HERO_HP 100
#define HERO_STATUS_MAX 5
#define HERO_IMG_MAX 7
#define HERO_CHANGE_INTERVAL 250
#define HERO_FIRE_INTERVAL 100
#define HERO_BULLET_WIDTH 5
#define HERO_BULLET_HEIGHT 10
#define HERO_BULLET_SPEED 10
#define HERO_BULLET_DAMAGE 100
#define HERO_BOMB_INIT_COUNT 3

#define ENEMY0_WIDTH 25
#define ENEMY0_HEIGHT 20
#define ENEMY0_SPEED 4
#define ENEMY0_HP 100
#define ENEMY0_SCORE 100
#define ENEMY0_APPEND_SCORE 30
#define ENEMY0_STATUS_MAX 5
#define ENEMY0_IMG_MAX 6

#define ENEMY1_WIDTH 40
#define ENEMY1_HEIGHT 49
#define ENEMY1_SPEED 3
#define ENEMY1_HP 200
#define ENEMY1_SCORE 1000
#define ENEMY1_STATUS_MAX 5
#define ENEMY1_IMG_MAX 7
#define ENEMY1_APPEND_SCORE 1000
#define ENEMY1_FIRE_INTERVAL 400
#define ENEMY1_BULLET_WIDTH 5
#define ENEMY1_BULLET_HEIGHT 10
#define ENEMY1_BULLET_SPEED 7
#define ENEMY1_BULLET_DAMAGE 40

#define ENEMY2_WIDTH 83
#define ENEMY2_HEIGHT 128
#define ENEMY2_SPEED 2
#define ENEMY2_HP 1000
#define ENEMY2_SCORE 10000
#define ENEMY2_STATUS_MAX 7
#define ENEMY2_IMG_MAX 10
#define ENEMY2_APPEND_SCORE 10000
#define ENEMY2_CHANGE_INTERVAL 200
#define ENEMY2_FIRE_INTERVAL 800
#define ENEMY2_BULLET_WIDTH 20
#define ENEMY2_BULLET_HEIGHT 20
#define ENEMY2_BULLET_SPEED 15
#define ENEMY2_BULLET_DAMAGE 200

#define HERO_HIT_DEV 0
#define ENEMY_HIT_DEV 10
#define CRASH_DEV 20

#define ALIVE_STATUS 0
#define DOWN_STATUS 1

#define APPEARANCE1 1
#define APPEARANCE2 2

#define BLACK { 0,0,0 }
#define RED { 255,0,0 }
#endif